# Generated by Django 4.2.1 on 2024-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop_app', '0005_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
