# Generated by Django 4.2 on 2024-07-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop_app', '0008_alter_rating_unique_together_reviewvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
